### ISSUE TITLE
Drag & drop files on page UI

### ISSUE THREAD

**Issue by didoda** [bedita/web#208]
UI for drag and drop on page (design + logic).

**Comment by vallo87** [comment]
Let's discuss about behavior, that's how I imagined it:

Premise panel is closed
Case A. 
Drag 1 file over viewport, panel open up, drop area is shown, drop happens, create new object for the file, then the options are: 
1. open the view for the newly created file
2. stay with panel open, show the newly created object and some attributes
3. stay with panel open, show the newly created object and if the main view is an object view shows the possible relations for the newly uploaded file to it (if there's any)  to chose from
4. close the panel and do nothing

Case B.
Drag More files over viewport, panel open up, drop area is shown, then the options are: 
1. stay with panel open, shows a list (with preview) of the new objects
2. stay with panel open, show the newly created objects and if the main view is an object view shows the possible relations for the newly uploaded file to it (if there's any) to chose from
3. close the panel and do nothing

if panel is open and if the action is relation-add then any compatible file will be created and "staged" for that relation.
if panel is open, stack that action and go back to it after drag drop events are over
