### ISSUE TITLE
Can't upload video file

### ISSUE THREAD

**Issue by vallo87** [bedita/web#222]
When i try to save a video this error happens

Error message:
```
Invalid form data: file.tmp_name

Error in: /Users/vallo/www/projects/be4-web/src/Controller/Component/ModulesComponent.php, line 218
```

Env:
- master
- feat/207-new-media-remove-upload-button

**Comment by didoda** [comment]
There was a problem in @vallo87 `php.ini`, with unexpected side effect.
He fixed `php.ini` config vars:
```
; Maximum allowed size for uploaded files.
upload_max_filesize = 20M 

; Must be greater than or equal to upload_max_filesize
post_max_size = 20M 
```

Now everything is fine.

**Comment by stefanorosanelli** [comment]
@didoda  Ok, can we have a more meaningful error message?

**Comment by didoda** [comment]
Not really. Php server silently let the post goes with an empty `file.tmp_file` (no warning, no error).
Ipotetically we could do "system check" in bootstrap, to prevent such kind of errors

**Comment by didoda** [comment]
We are going to handle properly upload errors (http://php.net/manual/en/features.file-upload.errors.php).
