### ISSUE TITLE
Proposal for composer scripts for docker

### ISSUE THREAD

**Issue by vallo87** [bedita/web#227]
I came up with a very simple script to have one command to test on a docker machine

container -> launch, wait, test on it, stop

```json
        "start-container": "docker run --rm -d -t -p 8090:80 --name=bedita_4_cactus_test_env --env BEDITA_ADMIN_USR=bedita --env BEDITA_ADMIN_PWD=bedita bedita/bedita:4-cactus",
        "wait-container": "sleep 1s",
        "test-container": "vendor/bin/phpunit --colors=always || true done",
        "stop-container": "docker stop bedita_4_cactus_test_env",
        "test-docker": [
            "@start-container",
            "@wait-container",
            "@test-container",
            "@stop-container"
        ]
```
the start-container should be check if container is already started or if image is not downloaded, etc..
the wait-container should be done in a meaningful way, so it really wait for the api to be ready

**Comment by stefanorosanelli** [comment]
Could be useful. 
Have a look in `.travis.yml` where we have
```
  - docker pull bedita/bedita:4-cactus
  - docker run -d -p 127.0.0.1:8080:80 --env BEDITA_API_KEY=${BEDITA_API_KEY} --env BEDITA_ADMIN_USR=${BEDITA_ADMIN_USR} --env BEDITA_ADMIN_PWD=${BEDITA_ADMIN_PWD} bedita/bedita:4-cactus
  - sleep 10
  - docker ps -a
```
A `pull` and `ps -a` step may be implemented.

A little problem is: env vars should match those defined in `tests/.env` or directly set here, in this case `tests/.env` must not be used.

Another solution is to customize these scripts in `composer.local.json`

**Comment by vallo87** [comment]
ok these are good suggestions, what about the "sleep 10" or sleep 1 in my proposal which i don't like at all... I tried to make a script which would check when a container is ready, but seamed rather complicated and yet not perfect
maybe with curl -s -H 'Accept: application/vnd.api+json' http://localhost:8090/home
we can see when api's ready and the start testing
